version: '3.7'
services:

  employees:
    image: genschsa/mysql-employees
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: groot
      MYSQL_PASSWORD: groot
      MYSQL_ROOT_PASSWORD: groot
    networks:
      - default

  sakila:
    image: sakiladb/mysql
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: groot
      MYSQL_PASSWORD: groot
      MYSQL_ROOT_PASSWORD: groot
    networks:
      - default

  puml:
    image: plantuml/plantuml-server:tomcat
    labels:
      - 'traefik.enable=true'
    environment:
      PLANTUML_LIMIT_SIZE: 10000
    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true

