version: '3.7'
services:

  employees:
    image: genschsa/mysql-employees
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: groot
      MYSQL_PASSWORD: groot
      MYSQL_ROOT_PASSWORD: groot
    networks:
      - default

  sakila:
    image: sakiladb/mysql
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: groot
      MYSQL_PASSWORD: groot
      MYSQL_ROOT_PASSWORD: groot
    networks:
      - default

networks:
  default:

